name: Send Secrets to EC2

on:
  push:
    branches:
      - master

jobs:
  send-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Send Secrets to EC2
        run: |
          echo "Sending secrets to EC2..."
          curl -X POST http://ec2-35-157-150-219.eu-central-1.compute.amazonaws.com:8501/secrets -H "Content-Type: application/json" -d '{"AIREDGIO_TEST_API": "${{ secrets.AIREDGIO_TEST_API }}", "AIOD_LOCAL_URL": "${{ secrets.AIOD_LOCAL_URL }}", "CLIENT_ID": "${{ secrets.CLIENT_ID }}", "CLIENT_SECRET": "${{ secrets.CLIENT_SECRET }}", "KEYCLOAK_LOCAL_URL": "${{ secrets.KEYCLOAK_LOCAL_URL }}", "KEYCLOAK_LOCAL_REALM": "${{ secrets.KEYCLOAK_LOCAL_REALM }}"}'
        env:
          AIREDGIO_TEST_API: ${{ secrets.AIREDGIO_TEST_API }}
          AIOD_LOCAL_URL: ${{ secrets.AIOD_LOCAL_URL }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          KEYCLOAK_LOCAL_URL: ${{ secrets.KEYCLOAK_LOCAL_URL }}
          KEYCLOAK_LOCAL_REALM: ${{ secrets.KEYCLOAK_LOCAL_REALM }}